package com.platform.http.api;

public enum HttpErrorCode {
    REQUEST_CONSTRUCTION_FAILED,
    SERIALIZATION_FAILED,
    CONNECTION_FAILED,
    DNS_FAILURE,
    TIMEOUT,
    TLS_FAILURE,
    DOWNSTREAM_CLIENT_ERROR,
    DOWNSTREAM_SERVER_ERROR,
    DESERIALIZATION_FAILED,
    FORWARDING_FAILED,
    MIDDLEWARE_FAILURE,
    UNEXPECTED
}
