package com.platform.security.api;

public enum SecurityEventType {
    AUTHENTICATION_STARTED,
    AUTHENTICATION_SUCCEEDED,
    AUTHENTICATION_FAILED,
    INVALID_TOKEN,
    TOKEN_EXPIRED,
    MALFORMED_TOKEN,
    MISSING_CREDENTIALS,
    AUTHORIZATION_STARTED,
    AUTHORIZATION_SUCCEEDED,
    AUTHORIZATION_FAILED,
    ACCESS_DENIED,
    MIDDLEWARE_FAILURE,
    SECURITY_CONTEXT_FAILURE,
    UNEXPECTED_ERROR,
    REQUEST_REJECTED,
    PROCESSING_COMPLETED
}
