package com.platform.http.events;

public enum HttpEventType {
    REQUEST_STARTED,
    REQUEST_CONSTRUCTION_FAILED,
    SERIALIZATION_FAILED,
    CONNECTION_FAILED,
    DNS_FAILURE,
    TIMEOUT,
    TLS_FAILURE,
    REQUEST_REJECTED,
    DOWNSTREAM_CLIENT_ERROR,
    DOWNSTREAM_SERVER_ERROR,
    DESERIALIZATION_FAILED,
    FORWARDING_FAILED,
    MIDDLEWARE_FAILURE,
    UNEXPECTED_ERROR,
    REQUEST_COMPLETED
}
